### ISSUE TITLE
fetching full original filenames

### ISSUE THREAD

**Issue by jszczypk** [patrickkfkan/imagefap-dl#2]
Downloaded files are stored as "xxxxxxxxxxxxxxxxx.. (photo-id).jpg" as this is the information available on gallery page.
However in individual photo page full original name is available in few tags: meta description, title, img title and img alt.

Can you add an option to fetch full filenames from individual photos pages?

Best regards,
Janusz

**Comment by jszczypk** [comment]
Here it is: https://www.imagefap.com/photo/1524182108/
Look for "its-beginning-to-looks-a-lot-like-christmas-0004.jpg" in HTML

**Comment by patrickkfkan** [comment]
Added `--full-filenames` (alias `-f`) option in v1.2.0.  You should now be able to have full original filename of images by doing:

```
$ imagefap-dl -f <url>
```
