### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by tejprokash** [patrickkfkan/imagefap-dl#3]
Suddenly I had a download problem. I am getting this code `Uncaught SyntaxError: Unexpected identifier 'imagefap'` in output. I have also done fresh installation, but nothing helps.

**Comment by patrickkfkan** [comment]
Do you get error just by running `imagefap-dl --help`?

Also, which URL format are you downloading from:
```
1.  https://www.imagefap.com/profile/<username>/galleries                                                                                                     
2.  https://www.imagefap.com/profile/<username>/galleries?folderid=<folder-id>  
3.  https://www.imagefap.com/organizer/<folder-id>/<folder-slug>                
4.  https://www.imagefap.com/usergallery.php?userid=<user-id>&folderid=<folder-id>
5.  https://www.imagefap.com/gallery/<gallery-id>                               
6.  https://www.imagefap.com/gallery.php?gid=<gallery-id>                       
7.  https://www.imagefap.com/pictures/<gallery-id>/<gallery-slug>
```

**Comment by tejprokash** [comment]
**At the time of fresh installation, I am getting this error:**
![Screenshot 2024-05-09 151946](https://github.com/patrickkfkan/imagefap-dl/assets/133680165/11018b5a-5f83-43de-9f6e-f339964beb95)

**While downloading, getting this error:**
![Screenshot 2024-05-09 152459](https://github.com/patrickkfkan/imagefap-dl/assets/133680165/9cdc1332-e08b-4e08-b8ff-8fdf96b05d6d)

**Comment by patrickkfkan** [comment]
Why are you in Node.js Command Prompt ?  Just use Windows Command Prompt - the one you used in the first screenshot.

**Comment by tejprokash** [comment]
Sorry, my bad.
Thank you for your help.
